name: flutter_contact
version: 0.9.2+8
homepage: https://github.com/SunnyApp/flutter_contact
description: A Flutter plugin to retrieve, create and save contacts and contact-related events on Android and iOS devices.
maintainer: Eric Martineau
environment: 
  sdk: ">=3.4.3 <4.0.0"
  flutter: '>=1.10.0'
dependencies: 
  collection: ^1.15.0
  dartxx: 
    git:
      url: https://github.com/WorkNedoPrograMax/dartxx.git
      ref: a907d29e1fc09bbe6fd9d3ef3768240e5b1bfc98
  equatable: 
  #flexidate: ^0.8.0+3
  flexidate:
    git:
      url: https://github.com/WorkNedoPrograMax/flexidate.git
      ref: 4e4315e2e3bbe1b1125c4b458ee26cdef18609f2
  #intl: ^0.17.0 jinaki 수정
  intl: 
  logging: ^1.0.2
  logging_config: ^0.6.7+7
  quiver: ^3.0.1+1
  uuid: ^3.0.5
  flutter: 
    sdk: flutter
dev_dependencies: 
  pedantic: ^1.11.1
  flutter_test: 
    sdk: flutter
flutter: 
  plugin: 
    platforms: 
      android: 
        package: co.sunnyapp.flutter_contact
        pluginClass: FlutterContactPlugin
      ios: 
        pluginClass: FlutterContactPlugin
